### ISSUE TITLE
defog gen tablename1,tablename2 - error

### ISSUE THREAD

**Issue by rayskan** [defog-ai/defog-python#38]
when i used single table its okay , but  defog gen multiple tables with comma sep. gets this below error and always
if single table metadata.csv is created , if i do another table, its not appended but only one is added .so trying multiple tables and gets below error. 
Fyi database is databricks

We are now uploading this auto-generated schema to Defog.
Traceback (most recent call last):
  File "/opt/homebrew/bin/defog", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/defog/cli.py", line 41, in main
    gen()
  File "/opt/homebrew/lib/python3.11/site-packages/defog/cli.py", line 312, in gen
    df.update_db_schema(filename)
  File "/opt/homebrew/lib/python3.11/site-packages/defog/admin_methods.py", line 10, in update_db_schema
    schema_df = pd.read_csv(path_to_csv).fillna("")
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/common.py", line 451, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>

**Comment by wongjingping** [comment]
Hi @rayskan I believe you should be using single spaces to delimit the table names.

**Comment by rayuduak** [comment]
@wongjingping 
Thanks you are right
I overlooked documentation 
Will try without spaces

**Comment by wongjingping** [comment]
Np, please feel free to reopen another issue if you face an issue with that.
