### ISSUE TITLE
Does defog ai support the database SQL server?

### ISSUE THREAD

**Issue by 892902296** [defog-ai/defog-python#50]
According to the guidelines：https://docs.defog.ai/getting-started
I tried to execute the command: defog init
when it comes to the question: What database are you using? Available options are: postgres, redshift, mysql, bigquery, snowflake, databricks, which means that it is currently not supported SQL server？
But according to the official website of Defog AI: https://defog.ai/supported-dbs/
![abc](https://github.com/defog-ai/defog-python/assets/48235767/a9a29a63-686f-4a42-9608-79ffcb65a30b)

so, does defog ai support the database SQL server? and if it does, which option should I choose?
besides, I have tried to choose mysql, but get the below error:

Traceback (most recent call last):
  File "C:\Users\89290\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\89290\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\MyLLMs\Project_DefogAI_API\venv\Scripts\defog.exe\__main__.py", line 7, in <module>
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\defog\cli.py", line 43, in main
    gen()
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\defog\cli.py", line 308, in gen
    filename = df.generate_db_schema(table_name_list, scan=scan)
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\defog\generate_schema.py", line 518, in generate_db_schema
    return self.generate_mysql_schema(
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\defog\generate_schema.py", line 220, in generate_mysql_schema
    conn = mysql.connector.connect(**self.db_creds)
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\mysql\connector\pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\mysql\connector\connection_cext.py", line 144, in __init__
    self.connect(**kwargs)
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\mysql\connector\abstracts.py", line 1360, in connect
    self._open_connection()
  File "E:\MyLLMs\Project_DefogAI_API\venv\lib\site-packages\mysql\connector\connection_cext.py", line 332, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.OperationalError: 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

I think this may be due to the program attempting to search for MySQL database instead of SQLserver database, which triggered a timeout error

**Comment by rishsriv** [comment]
Hi there, we do support SQLServer. But unfortunately, it's for our enterprise customers and requires a bit more setup. It will not work well with our free and self-serve API and the `defog-python` library.

We will to add it to our free plan if we see enough demand for it (as it requires a dedicated GPU to run).

**Comment by rishsriv** [comment]
Hi there, we now have enough demand for SQLServer - and it is now a part of our free plan. You can run `pip install --upgrade defog`, then `defog init`, and can then enter your db credentials to start querying.
