### ISSUE TITLE
error bigquery defog gen command : too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by aburnazy** [defog-ai/defog-python#6]
Defog install failed with the following error when trying to generate the schema for bigquery.
The schema consisted of only 2 tables, 12 and 2 columns respectively.

`(base) c:\Users\aburnazyan\AppData\Roaming\Python\Python39\Scripts>defog gen  miabanutyun-84e26.fb_dataset.fb_data  miabanutyun-84e26.fb_dataset.members
Connection details found. Reading connection details from file...
Connection details read from C:\Users\aburnazyan\.defog\connection.json.
Getting the schema for each table in your database...
Sending the schema to Defog servers and generating a Google Sheet. This might take up to 2 minutes...
{'status': 'error', 'message': 'too many values to unpack (expected 2)'}
Traceback (most recent call last):
  File "C:\Users\aburnazyan\AppData\Roaming\Python\Python39\site-packages\defog\__init__.py", line 618, in generate_bigquery_schema
    gsheet_url = resp["sheet_url"]
KeyError: 'sheet_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\aburnazyan\AppData\Roaming\Python\Python39\Scripts\defog.exe\__main__.py", line 7, in <module>
  File "C:\Users\aburnazyan\AppData\Roaming\Python\Python39\site-packages\defog\cli.py", line 41, in main
    gen()
  File "C:\Users\aburnazyan\AppData\Roaming\Python\Python39\site-packages\defog\cli.py", line 258, in gen
    gsheets_url = df.generate_db_schema(table_name_list)
  File "C:\Users\aburnazyan\AppData\Roaming\Python\Python39\site-packages\defog\__init__.py", line 634, in generate_db_schema
    return self.generate_bigquery_schema(tables)
  File "C:\Users\aburnazyan\AppData\Roaming\Python\Python39\site-packages\defog\__init__.py", line 622, in generate_bigquery_schema
    raise resp["message"]
TypeError: exceptions must derive from BaseException`

**Comment by wongjingping** [comment]
Hi @aburnazy, thanks for raising this issue. We've identifed and fixed the issue on our backend (not an issue with this client), and also updated the client to print out a more informative message (see #7). Could you try again and let us know if you still encounter the same issue!

**Comment by aburnazy** [comment]
Just re-run the **defog init** - now the error points out that:
```
{'status': 'error', 'message': 'Please verify your email before using this feature. You can get a new verification email by logging in to your account, and clicking "resend".'}
```

Fair enough I haven't.
However logging in to the system again as the error message suggests I can not find where the Resend button is.

**Comment by aburnazy** [comment]
@wongjingping @NirantK @rishsriv any help appreciated.

**Comment by wongjingping** [comment]
Hi @aburnazy, could you drop us (support (at) defog.ai) a private email with your api key - we can help to retrigger the email verification flow. We will be closing this issue as this doesn't relate to the repository in question.
